version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dl-app-api
    restart: unless-stopped
    ports:
      - "8040:8040"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PROD_PORT:-8040}
    networks:
      - dl-app-network

networks:
  dl-app-network:
    driver: bridge
